import React from "react";
import Layout from "../../components/Layout";
import SEO from "../../components/Seo";
import Cookies from "../../components/Cookies";

import { PrivacyPolicyStyle } from "./styles";

export default function PagePricing() {
  return (
    <Layout>
      <SEO
        title="Privacy Policy"
        description="Shell hub privacy policy, listing what cookies are used for collecting data from our users, and how it improves your experience when using our application"
        lang="en"
      />
      <PrivacyPolicyStyle>
        <div className="container">
          <div className="title">
            <h1>Privacy Policy</h1>
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>
          </div>

          <div className="content">
            <h1>Definitions</h1>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li>
                <span>Account:</span> means a unique account created for You to
                access our Service or parts of our Service.
              </li>

              <li>
                <span>Company:</span> refers to ShellHub.
              </li>

              <li>
                <span>Cookies:</span> are small files that are placed on Your
                computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </li>
              <li>
                <span>Country:</span> refers to: Brazil.
              </li>

              <li>
                <span>Device:</span> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>

              <li>
                <span>Personal Data:</span> is any information that relates to
                an identified or identifiable individual.
              </li>

              <li>
                <span>Service Provider :</span> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used..
              </li>

              <li>
                <span>Third-party Social Media Service:</span> refers to:
                Brazil.
              </li>

              <li>
                <span>Device:</span> refers to any website or any social network
                website through which a User can log in or create an account to
                use the Service.
              </li>

              <li>
                <span>Usage Data:</span> efers to data collected automatically,
                either generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </li>

              <li>
                <span>Website:</span> refers to ShellHub, accessible from
                <a href="https://www.shellhub.io/">shellhub</a>
              </li>

              <li>
                <span>You:</span> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
          </div>

          <div className="content">
            <h1>Collecting and Using Your Personal Data</h1>
            <p>Types of Data Collected:</p>

            <ul>
              <li>
                <span className="data-title">Personal Data:</span>
                <p>
                  While using Our Service, We may ask You to provide Us with
                  certain personally identifiable information that can be used
                  to contact or identify You. Personally identifiable
                  information may include, but is not limited to:
                </p>

                <ul className="inside-ul">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                </ul>
              </li>

              <li>
                <span className="data-title">Usage Data:</span>
                <p>
                  Usage Data is collected automatically when using the Service.
                </p>
                <p>
                  Usage Data may include information such as Your Device's
                  Internet Protocol address (e.g. IP address), browser type,
                  browser version, the pages of our Service that You visit, the
                  time and date of Your visit, the time spent on those pages,
                  unique device identifiers and other diagnostic data.
                </p>

                <p>
                  When You access the Service by or through a mobile device, We
                  may collect certain information automatically, including, but
                  not limited to, the type of mobile device You use, Your mobile
                  device unique ID, the IP address of Your mobile device, Your
                  mobile operating system, the type of mobile Internet browser
                  You use, unique device identifiers and other diagnostic data.
                </p>

                <p>
                  We may also collect information that Your browser sends
                  whenever You visit our Service or when You access the Service
                  by or through a mobile device.
                </p>
              </li>
            </ul>
          </div>

          <div className="content">
            <h1>Children's Privacy</h1>
            <p>
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us. If We become aware that We have collected Personal
              Data from anyone under the age of 13 without verification of
              parental consent, We take steps to remove that information from
              Our servers.
            </p>

            <p>
              If We need to rely on consent as a legal basis for processing Your
              information and Your country requires consent from a parent, We
              may require Your parent's consent before We collect and use that
              information.
            </p>
          </div>

          <div className="content">
            <h1>Links to Other Websites</h1>
            <p>
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party's site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>

            <p>
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
          </div>

          <div className="content">
            <h1>Changes to this Privacy Policy</h1>
            <p>
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>

            <p>
              We will let You know via email and/or a prominent notice on Our
              Service, prior to the change becoming effective and update the
              "Last updated" date at the top of this Privacy Policy.
            </p>

            <p>
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </div>

          <div className="content">
            <h1>Contact Us</h1>
            <p>
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>

            <ul className="inside-ul">
              <li>By email: contato@ossystems.com</li>
              <li>
                By visiting this page on our website:
                <a href="https://www.shellhub.io/contact">ShellHub</a>
              </li>
            </ul>
          </div>
        </div>

        <Cookies />
      </PrivacyPolicyStyle>
    </Layout>
  );
}
